messages:
  give_booster_syntax: "&a&l[TerraBoosters] &e/boosters give <player> <booster> <amount>"
  command_only_ingame: "&a&l[TerraBoosters] &cThis is an exclusive command for in-game players."
  booster_not_found: "&a&l[TerraBoosters] &cBooster {boosterId} not found."
  player_not_online: "&a&l[TerraBoosters] &cPlayer not found."
  player_inventory_full: "&a&l[TerraBoosters] &cPlayer {playerName} is full of items."
  booster_gave: "&a&l[TerraBoosters] &eYou gave {boosterAmount}x {boosterName} &eboosters to {receiverName}"
  booster_already_in_use: "&a&l[TerraBoosters]{@}&cThere's a booster with the same skill running."
  booster_consumed: "&a&l[TerraBoosters]{@}&eBooster {boosterName} &estarted and will expire in {boosterExpiration}"

settings:
  date_format: "dd/MM/yyyy HH:mm"
  storage:
    type: SQL

boosters:
  0:
    name: "&d&lMINER"
    duration: 3600
    multiplication: 2
    skill: MINING
    item:
      id: EXPERIENCE_BOTTLE
      name: '&e&lBOOSTER'
      description:
        - '&7Type: &d&lMINER (MCMMO)'
        - ''
        - ' &8* &aWith this booster, you will'
        - ' &areceive 2.0x more than usual'
        - ''
        - ' &7Multiplier: &f2.0x'
        - ' &7Duration: &f1 hour'
        - ''
      glow: true